# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt

# Run the unit test
script:
  - coverage run -m unittest

# Push the results back to codecov
after_success:
  - codecov
