overrides:
  Chapter 1 The Promise: 'Chapter 1: The Promise'
  New York 1942: New York, 1942
  Part 1 The Reckoning: 'Part 1: The Reckoning'
  Part 2 The Whatever: 'Part 2: The Whatever'
  Part 3 Tomorrow: 'Part 3: Tomorrow'
