
# Governs if section, chapter, and sub-chapter headers are showing when compiled
headers:
  section: true
  chapter: true
  sub_chapter: true

# Select 'false' to disable COMMIT warnings
warnings:
  parse: true
  split: true
  sequence: true
  trim: true

# Use to override title, section, chapter, or sub-chapter names.
# Useful for including punctuation since
# Example override -- Chapter 1 Looming: Chapter 1: Looming
overrides:
